### PR TITLE
New content for CPP 

### PR DESCRIPTION
**Pull request by malwaru**
Added in WS21 . Removed unnecessary binary files and line spacing in the code

### CODE REVIEW

**Review by malwaru — COMMENTED** [review]
Added new teaching material for the cpp files

**Comment by malwaru** [comment]
Want to retry creating the pull request with assigned reviewer

**Comment by alex-mitrevski** [comment]
Hi @malwaru, in your PR title, you say this is content for C++, but I see changes in the Python exercise notebooks as well. Could you please describe what these changes are and change the title accordingly? Also, please remove the vscode settings file.

**Comment by malwaru** [comment]
Made a new commit with removing vscode files and replacing the modified ipython file with the original file from the main repo

**Review by alex-mitrevski — APPROVED** [review]

**Comment by alex-mitrevski** [comment]
@malwaru I have merged the PR. Thanks!

**Pull request merged**
